### ISSUE TITLE
File-Find-utf8-0.013 tests have started to fail

### ISSUE THREAD

**Issue by andk** [HayoBaan/File-Find-utf8#3]
Sample fail report: http://www.cpantesters.org/cpan/report/ef4ca4d4-f896-11eb-a349-bc668d979bbb

Bisect on bleadperl leads to the commit https://github.com/perl/perl5/commit/c108140682f

**Comment by HayoBaanAtHand** [comment]
Hi Andreas,

Many thanks for investigating! I saw the failure reports but could not think of any reason whey `export` would no longer work (certainly as the only method I call is `Exporter::export_to_level`, and I call that directly, I don't reference `export` directly at all), so wrote the failures off as (temporary) flukes.

Looking at the commit you referenced, there indeed seem to be changes related to the Exporter module. However, as I can not reproduce the problem on my system (v5.34.0), I'm a little bit in the dark as to how I could fix this. I'm also not sure the error is actually in my code or in the base `File::Find`?

What I do see when looking at the `Exporter::Heavy` library code is indeed a reference to `export` at the current package. So perhaps changing line 157 in my `File::Find::utf8` from `require Exporter;` to e.g. `require Exporter qw(export);` would work. Can you try that?

Thanks,
Hayo

**Comment by HayoBaan** [comment]
Hi Andreas,

Many thanks for investigating! I saw the failure reports but could not think of any reason whey export would no longer work (certainly as the only method I call is Exporter::export_to_level, and I call that directly, I don't reference export directly at all), so wrote the failures off as (temporary) flukes.

Looking at the commit you referenced, there indeed seem to be changes related to the Exporter module. However, as I can not reproduce the problem on my system (v5.34.0), I'm a little bit in the dark as to how I could fix this. I'm also not sure the error is actually in my code or in the base File::Find?

What I do see when looking at the Exporter::Heavy library code is indeed a reference to export at the current package. So perhaps changing line 157 in my File::Find::utf8 from require Exporter; to e.g. require Exporter qw(export); would work. Can you try that?

Thanks,
Hayo

**Comment by andk** [comment]
I'm very sorry, Hayo, this goes far above my level of experience. I try summoning @Corion : Max, can you please help here?

@HayoBaan : if Max does not answer, please try to contact Perl5 directly. There surely will somebody be able to help you.

**Comment by andk** [comment]
I have opened https://github.com/Perl/perl5/issues/19427 
I'm sorry I didn't do this immediately. One never knows how complicated it gets

**Comment by haarg** [comment]
File::Find::utf8 is calling `Exporter::export_to_level("File::Find", 1, ...)`. export_to_level is normally a class method, so it expects that it can call Exporter methods via the first parameter. File::Find has been changed to no longer inherit from Exporter, so those methods no longer exist on File::Find.

One possible fix would be to change
```
Exporter::export_to_level($original_package, 1, $target_package, @_) if (@_);
```
to
```
if (@_) {
    @_ = ($original_package, @_);
    goto &Exporter::import;
}
```

**Comment by HayoBaan** [comment]
Thank you Graham, I've updated the code as you suggested. Let's hope this works!

**Comment by Corion** [comment]
Sorry for being so late to reply. I confirm that the change proposed by @haarg works for my build of bleadperl at 5.35.9. Thank you very much @andk for running the smoke testers and finding the breakage before a stable release goes out!

**Comment by HayoBaan** [comment]
The test reports have been rolling in now and the fix is working – also for the newer Perl versions. Closing the issue.
